-- Rollback fixtures only. Written, not executed or applied to a live database.
begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public,extensions;
grant usage on schema extensions to anon,authenticated;
do $$declare f regprocedure;begin
 for f in select p.oid::regprocedure from pg_proc p join pg_depend d on d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e'
 join pg_extension e on e.oid = d.refobjid where e.extname = 'pgtap'
 loop execute format('grant execute on function %s to anon,authenticated',f);end loop;
end;$$;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,is_anonymous,raw_user_meta_data)
 select ('39000000-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid,'tier-pub-' || n || '@example.test',now(),false,'{"role":"admin"}' from generate_series(1,3) n;
-- Local transactional fixtures only: shared Auth identities do not auto-enroll.
insert into public.toon_profiles(id) select id from auth.users where id::text like '39000000-0000-4000-8000-%' on conflict(id) do nothing;
insert into public.toon_user_settings(user_id) select id from public.toon_profiles where id::text like '39000000-0000-4000-8000-%' on conflict(user_id) do nothing;
insert into toon_private.toon_user_access(user_id) select id from public.toon_profiles where id::text like '39000000-0000-4000-8000-%' on conflict(user_id) do nothing;
insert into auth.sessions(id,user_id,created_at,updated_at)
 select ('49000000-0000-4000-8000-' || right(id::text,12))::uuid,id,now(),now() from auth.users where id::text like '39000000-%';
update public.toon_profiles set username = 'tier_pub_' || right(id::text,1),display_name = '[테스트] 게시',onboarding_completed_at = now() where id::text like '39000000-%';
update toon_private.toon_user_access set status = 'active',role = case when right(user_id::text,1) = '1' then 'admin'::public.toon_user_role else 'user'::public.toon_user_role end where user_id::text like '39000000-%';
insert into toon_private.toon_consent_records(user_id,policy_kind,version)
 select p.id,k,'2026-10-02-preview' from public.toon_profiles p cross join unnest(array['terms','privacy','age_14']) k where p.id::text like '39000000-%';
insert into public.toon_works(id,slug,title,age_rating,catalogue_status)
 select ('59000000-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid,'tier-pub-' || n,'[테스트] 게시 작품 ' || n,'all','published' from generate_series(1,3) n;
insert into public.toon_work_platforms(work_id,platform_id,official_url,age_rating,verified_at)
 select w.id,p.id,'https://comic.naver.com/toonshelf-test-only/' || w.slug,'all',now() from public.toon_works w cross join public.toon_platforms p where w.id::text like '59000000-%' and p.code = 'naver_webtoon';
create function public.toon_test_tier_pub_payload() returns jsonb language sql set search_path = '' as $$select '{"title":"publication-spoiler-secret","description":"snapshot-description","tags":["snapshot-tag"],"rows":[{"id":"69000000-0000-4000-8000-000000000001","label":"S custom","colorToken":"S","canonicalTier":null},{"id":"69000000-0000-4000-8000-000000000002","label":"A","colorToken":"A","canonicalTier":"A"}],"placements":[{"workId":"59000000-0000-4000-8000-000000000001","rowId":"69000000-0000-4000-8000-000000000001","position":0},{"workId":"59000000-0000-4000-8000-000000000002","rowId":"69000000-0000-4000-8000-000000000002","position":0},{"workId":"59000000-0000-4000-8000-000000000003","rowId":null,"position":0}]}'::jsonb;$$;
create function public.toon_test_tier_envelope(p_hash text) returns jsonb language sql set search_path = '' as $$select jsonb_build_object('hash',repeat(p_hash,64),'ciphertext',repeat('b',118),'nonce',repeat('c',24));$$;
grant execute on function public.toon_test_tier_pub_payload(),public.toon_test_tier_envelope(text) to authenticated;
select ok(not has_table_privilege('anon','public.toon_tier_list_publications','SELECT'),'Anonymous has no raw publication SELECT');
select ok(not has_table_privilege('authenticated','public.toon_tier_list_publications','SELECT'),'Owners also use current-reader RPCs');
select ok(not has_table_privilege('authenticated','toon_private.toon_tier_share_tokens','SELECT'),'No direct encrypted token SELECT');
select ok(not has_function_privilege('authenticated','toon_private.toon_tier_put_token(uuid,jsonb)','EXECUTE'),'No direct token helper access');
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_pub.id',public.toon_create_tier_draft(public.toon_test_tier_pub_payload(),null)::text,true);
select set_config('tier_pub.preview',public.toon_preview_tier_publication(current_setting('tier_pub.id')::uuid)::text,true);
select is(jsonb_array_length(current_setting('tier_pub.preview')::jsonb->'body'->'rows'->0->'items'),1,'Preview includes placed works');
select throws_ok($$select public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,1,1,current_setting('tier_pub.preview')::jsonb->>'fingerprint','public',true,null,false)$$,'P0001','VALIDATION_ERROR','Publication requires explicit confirmation');
select is(public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,1,1,current_setting('tier_pub.preview')::jsonb->>'fingerprint','public',true,null,true)->>'version','2','Publication increments independent lifecycle version');
select is(public.toon_save_tier_draft(current_setting('tier_pub.id')::uuid,1,jsonb_set(public.toon_test_tier_pub_payload(),'{title}','"autosave-private-secret"'))->>'version','2','Autosave only changes draft');
select throws_ok($$select public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,1,2,current_setting('tier_pub.preview')::jsonb->>'fingerprint','public',true,null,true)$$,'P0001','CONFLICT','Stale saved preview cannot be published');
reset role;
select is((select jsonb_array_length(payload->'placements') from public.toon_tier_list_publications where tier_list_id = current_setting('tier_pub.id')::uuid),2,'Immutable publication excludes unplaced works');
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,false,null)->'body','null'::jsonb,'Spoiler body omitted on initial read');
select ok(public.toon_list_public_tiers(1)::text !~ 'publication-spoiler-secret|snapshot-description|snapshot-tag','Public list has no spoiler text');
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,2)->'body'->>'title','publication-spoiler-secret','Saved draft changes do not replace publication');
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,1),null::jsonb,'Publication number is not a stale lifecycle capability');
select throws_ok('select * from public.toon_tier_list_publications','42501',null,'Direct REST-equivalent read is denied');
reset role;
update public.toon_works set catalogue_status = 'hidden' where id = '59000000-0000-4000-8000-000000000002';
set local role anon;
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,2)->'body'->'rows'->1->'items'->0,'null'::jsonb,'Newly hidden work becomes a non-identifying placeholder');
select ok(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,2)::text !~ '59000000-0000-4000-8000-000000000002','Hidden work UUID is not disclosed in DTO');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_pub.preview',public.toon_preview_tier_publication(current_setting('tier_pub.id')::uuid)::text,true);
select is(public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,2,2,current_setting('tier_pub.preview')::jsonb->>'fingerprint','unlisted',true,public.toon_test_tier_envelope('a'),true)->>'version','3','Unlisted publication has its own current snapshot and token');
select is(public.toon_get_my_tier_share_token(current_setting('tier_pub.id')::uuid,3)->>'hash',repeat('a',64),'Owner can recover encrypted token material');
select is(public.toon_save_tier_draft(current_setting('tier_pub.id')::uuid,2,jsonb_set(public.toon_test_tier_pub_payload(),'{title}','"never-published-private-draft"'))->>'version','3','Later private edit stays private');
reset role;
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,false,null),null::jsonb,'Unlisted cannot be read by UUID');
select is(jsonb_array_length(public.toon_list_public_tiers(1)->'items'),0,'Unlisted is absent from ordinary public lists');
select is(public.toon_get_tier_publication(null,repeat('d',64),false,null),null::jsonb,'Invalid token hash reveals nothing');
select is(public.toon_get_tier_publication(null,repeat('a',64),false,null)->>'id',current_setting('tier_pub.id'),'Valid capability resolves current publication only');
reset role;
update toon_private.toon_tier_share_tokens set expires_at = now() - interval '1 second' where tier_list_id = current_setting('tier_pub.id')::uuid;
set local role anon;
select is(public.toon_get_tier_publication(null,repeat('a',64),false,null),null::jsonb,'Expired capability cannot read the publication');
reset role;
update toon_private.toon_tier_share_tokens set expires_at = null where tier_list_id = current_setting('tier_pub.id')::uuid;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000003","session_id":"49000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select is(public.toon_preview_tier_publication(current_setting('tier_pub.id')::uuid),null::jsonb,'Another owner cannot preview private draft');
select is(public.toon_get_my_tier_share_token(current_setting('tier_pub.id')::uuid,3),null::jsonb,'Another owner cannot recover encrypted token');
select set_config('tier_pub.clone',public.toon_clone_tier_publication(current_setting('tier_pub.id')::uuid,repeat('a',64),3,true)::text,true);
select is(public.toon_get_my_tier_editor(current_setting('tier_pub.clone')::uuid)->'draft'->>'title','autosave-private-secret (복사)','Clone uses publication, not newer private draft');
select is(jsonb_array_length(public.toon_get_my_tier_editor(current_setting('tier_pub.clone')::uuid)->'draft'->'placements'),1,'Clone omits unavailable and unplaced works');
select lives_ok($$select public.toon_report_tier_publication(current_setting('tier_pub.id')::uuid,repeat('a',64),'spoiler','[테스트] 스포일러 표시 확인이 필요합니다.')$$,'Accessible unlisted content can be reported');
select lives_ok($$select public.toon_report_tier_publication(current_setting('tier_pub.id')::uuid,repeat('a',64),'spoiler','[테스트] 중복 신고입니다. 원래 접수를 유지해 주세요.')$$,'Pending report retries do not create duplicates');
select is(jsonb_array_length(public.toon_list_my_tier_reports(1)->'items'),1,'Reporter sees only their own request');
select throws_ok($$select public.toon_moderation_tier_snapshot(current_setting('tier_pub.id')::uuid)$$,'P0001','FORBIDDEN','User-editable admin metadata grants no moderation');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000001","session_id":"49000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select ok(public.toon_moderation_tier_snapshot(current_setting('tier_pub.id')::uuid)::text !~ 'never-published-private-draft|ciphertext|token_hash','Moderator receives current publication, not private draft/token');
select set_config('tier_pub.report',(public.toon_list_tier_reports(1)->'items'->0->>'id'),true);
select lives_ok($$select public.toon_moderate_tier_publication(current_setting('tier_pub.id')::uuid,3,'hide','[테스트] 게시본 숨김',current_setting('tier_pub.report')::uuid,'[테스트] 숨김 처리')$$,'Moderation changes visibility and report result atomically');
select lives_ok($$select public.toon_moderate_tier_publication(current_setting('tier_pub.id')::uuid,4,'restore','[테스트] 숨김 해제',null,'')$$,'Restore does not republish or revive revoked capability');
reset role;
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select is(public.toon_get_tier_publication(null,repeat('a',64),false,null),null::jsonb,'Restored content does not revive old token');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.toon_rotate_tier_share_token(current_setting('tier_pub.id')::uuid,5,public.toon_test_tier_envelope('d'),true)->>'version','6','Only owner can issue replacement capability');
select is(jsonb_array_length(public.toon_list_my_tier_reports(1)->'items'),0,'Author does not receive reporter detail');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000003","session_id":"49000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select is(public.toon_list_my_tier_reports(1)->'items'->0->>'result','[테스트] 숨김 처리','Reporter can read moderation outcome');
select lives_ok($$select public.toon_set_user_block('39000000-0000-4000-8000-000000000002',true)$$,'Block author');
select is(public.toon_get_tier_publication(null,repeat('d',64),false,null),null::jsonb,'Block is rechecked for capability reads');
select throws_ok($$select public.toon_clone_tier_publication(current_setting('tier_pub.id')::uuid,repeat('d',64),6,true)$$,'P0001','NOT_FOUND','Block also prevents cloning through direct RPC');
select lives_ok($$select public.toon_set_user_block('39000000-0000-4000-8000-000000000002',false)$$,'Unblock author');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.toon_withdraw_tier_publication(current_setting('tier_pub.id')::uuid,6,true)->>'visibility','private','Withdraw clears public current pointer');
select is(public.toon_get_tier_publication(null,repeat('d',64),true,7),null::jsonb,'Withdrawal revokes token and content access');
select set_config('tier_pub.preview',public.toon_preview_tier_publication(current_setting('tier_pub.id')::uuid)::text,true);
select is(public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,3,7,current_setting('tier_pub.preview')::jsonb->>'fingerprint','public',false,null,true)->>'publishedVersion','3','Re-publication never reuses historical snapshot numbers');
reset role;
update public.toon_works set catalogue_status = 'published' where id = '59000000-0000-4000-8000-000000000002';
select is((select count(*)::integer from public.toon_user_evaluations where user_id::text like '39000000-%'),0,'Publishing and cloning never add canonical evaluations');
update toon_private.toon_user_access set status = 'suspended' where user_id = '39000000-0000-4000-8000-000000000002';
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,false,null),null::jsonb,'Suspended author is rechecked on public reads');
select is(jsonb_array_length(public.toon_list_public_tiers(1)->'items'),0,'Suspended author is removed from public lists');
reset role;
update toon_private.toon_user_access set status = 'active' where user_id = '39000000-0000-4000-8000-000000000002';
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000001","session_id":"49000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_pub.merge',public.toon_admin_merge_preview('59000000-0000-4000-8000-000000000001','59000000-0000-4000-8000-000000000002')::text,true);
select ok((current_setting('tier_pub.merge')::jsonb->>'canMerge')::boolean,'Publication domain has a preservation handler');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_pub.preview',public.toon_preview_tier_publication(current_setting('tier_pub.id')::uuid)::text,true);
select is(public.toon_publish_tier_list(current_setting('tier_pub.id')::uuid,3,8,current_setting('tier_pub.preview')::jsonb->>'fingerprint','public',false,null,true)->>'version','9','Publication update changes merge fingerprint');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000001","session_id":"49000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.toon_admin_merge_works('59000000-0000-4000-8000-000000000001','59000000-0000-4000-8000-000000000002',1,1,'[테스트] 동일 작품',true,(current_setting('tier_pub.merge')::jsonb->>'previewToken')::uuid,'latest_private')$$,'P0001','MERGE_PREVIEW_EXPIRED','Publication changes invalidate an old merge preview');
select set_config('tier_pub.merge',public.toon_admin_merge_preview('59000000-0000-4000-8000-000000000001','59000000-0000-4000-8000-000000000002')::text,true);
select lives_ok($$select public.toon_admin_merge_works('59000000-0000-4000-8000-000000000001','59000000-0000-4000-8000-000000000002',1,1,'[테스트] 동일 작품',true,(current_setting('tier_pub.merge')::jsonb->>'previewToken')::uuid,'latest_private')$$,'Draft/publication merge is atomic');
reset role;
select is((select payload->'placements'->0->>'workId' from public.toon_tier_list_publications where tier_list_id = current_setting('tier_pub.id')::uuid and version = 4),'59000000-0000-4000-8000-000000000001','Original publication remains immutable after merge');
select set_config('request.jwt.claims','{"role":"anon"}',true);
set local role anon;
select is(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,9),null::jsonb,'Merge invalidates stale reveal version');
select is(jsonb_array_length(public.toon_get_tier_publication(current_setting('tier_pub.id')::uuid,null,true,10)->'body'->'rows'->0->'items'),0,'Source duplicate resolves to existing target placement');
reset role;
select set_config('request.jwt.claims','{"sub":"39000000-0000-4000-8000-000000000002","session_id":"49000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.toon_delete_tier_draft(current_setting('tier_pub.id')::uuid,4,true)$$,'Deleting a tier also withdraws its publications');
reset role;
select is((select count(*)::integer from public.toon_tier_list_publications where tier_list_id = current_setting('tier_pub.id')::uuid),0,'Delete purges snapshot contents');
select is((select count(*)::integer from toon_private.toon_tier_share_tokens where tier_list_id = current_setting('tier_pub.id')::uuid),0,'Delete purges encrypted capability');
select * from finish();
rollback;
