-- Rollback fixtures only. Written, not executed/applied. Single-session checks;
-- pair-lock concurrency requires separate requested multi-session verification.
begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public,extensions;
grant usage on schema extensions to anon,authenticated;
do $$declare f regprocedure;begin
 for f in select p.oid::regprocedure from pg_proc p join pg_depend d on d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e'
 join pg_extension e on e.oid = d.refobjid where e.extname = 'pgtap'
 loop execute format('grant execute on function %s to anon,authenticated',f);end loop;
end;$$;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,is_anonymous,raw_user_meta_data)
 select ('3c000000-0000-4000-8000-' || lpad(n::text,12,'0'))::uuid,'tier-like-' || n || '@example.test',now(),false,'{"role":"admin"}' from generate_series(1,4) n;
insert into auth.sessions(id,user_id,created_at,updated_at)
 select ('4c000000-0000-4000-8000-' || right(id::text,12))::uuid,id,now(),now() from auth.users where id::text like '3c000000-%';
update public.profiles set username = 'tier_like_' || right(id::text,1),onboarding_completed_at = now() where id::text like '3c000000-%';
update private.user_access set status = 'active',role = case when right(user_id::text,1) = '4' then 'admin'::public.user_role else 'user'::public.user_role end where user_id::text like '3c000000-%';
insert into private.consent_records(user_id,policy_kind,version)
 select p.id,k,'2026-10-02-preview' from public.profiles p cross join unnest(array['terms','privacy','age_14']) k where p.id::text like '3c000000-%';
create function public.test_like_payload() returns jsonb language sql set search_path = '' as $$select '{"title":"like-test-spoiler-secret","description":"private description","tags":[],"rows":[{"id":"6c000000-0000-4000-8000-000000000001","label":"S","colorToken":"S","canonicalTier":"S"},{"id":"6c000000-0000-4000-8000-000000000002","label":"F","colorToken":"F","canonicalTier":"F"}],"placements":[]}'::jsonb;$$;
grant execute on function public.test_like_payload() to authenticated;
select ok(not has_table_privilege('authenticated','public.reactions','SELECT'),'No direct liker identity reads');
select ok(not has_table_privilege('authenticated','public.reactions','INSERT'),'No direct reactions DML');
select ok(not has_function_privilege('anon','public.set_tier_like(uuid,bigint,boolean)','EXECUTE'),'Anonymous cannot mutate likes');
select ok(not has_function_privilege('authenticated','private.tier_like_count(uuid)','EXECUTE'),'Private count helper cannot bypass target access');
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000001","session_id":"4c000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_like.id',public.create_tier_draft(public.test_like_payload(),null)::text,true);
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Private draft has no like state even for owner');
select set_config('tier_like.preview',public.preview_tier_publication(current_setting('tier_like.id')::uuid)::text,true);
select lives_ok($$select public.publish_tier_list(current_setting('tier_like.id')::uuid,1,1,current_setting('tier_like.preview')::jsonb->>'fingerprint','public',true,null,true)$$,'Publish a spoiler tier');
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)$$,'P0001','SELF_REACTION','Self-like is denied despite forged metadata role');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000002","session_id":"4c000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)->>'likeCount','1','First like counts once');
select is(public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)->>'likeCount','1','Repeated desired state is idempotent');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'liked','true','Current active member sees own state');
reset role;
select is((select count(*) from public.reactions where tier_list_id = current_setting('tier_like.id')::uuid),1::bigint,'Unique target row, no inflated counter');
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000003","session_id":"4c000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
set local role authenticated;
select is(public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)->>'likeCount','2','Second member counts independently');
reset role;
select set_config('request.jwt.claims','{}',true);
set local role anon;
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','2','Anonymous sees only current aggregate');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'canLike','false','Anonymous cannot like');
select is(public.get_tier_publication(current_setting('tier_like.id')::uuid,null,false,null)->>'likeCount','2','Current detail includes actual count');
select is(public.get_tier_publication(current_setting('tier_like.id')::uuid,null,false,null)->'body','null'::jsonb,'Like count does not reveal spoiler body');
select is(public.list_public_tiers(1)->'items'->0->>'likeCount','2','Existing list RPC includes aggregate without per-card network reads');
select ok(public.get_tier_like_state(current_setting('tier_like.id')::uuid)::text !~ '3c000000|user_id|description|spoiler-secret','State has no liker identities or content');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000002","session_id":"4c000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select is(public.set_tier_like(current_setting('tier_like.id')::uuid,2,false)->>'likeCount','1','Cancel removes only current actor');
select is(public.set_tier_like(current_setting('tier_like.id')::uuid,2,false)->>'likeCount','1','Repeated cancel is idempotent');
select lives_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)$$,'Like again');
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,1,false)$$,'P0001','CONFLICT','Old publication version cannot alter a current reaction');
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000003',true)$$,'Viewer blocks another reactor');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','1','Viewer does not count a blocked member');
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000003',false)$$,'Unblock another reactor');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','2','Other author reactions were not destructively removed');
reset role;
update private.user_access set status = 'suspended' where user_id = '3c000000-0000-4000-8000-000000000003';
set local role authenticated;
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','1','Suspended reactors are excluded dynamically');
reset role;
update private.user_access set status = 'active' where user_id = '3c000000-0000-4000-8000-000000000003';
update private.user_access set status = 'suspended' where user_id = '3c000000-0000-4000-8000-000000000001';
set local role authenticated;
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Inactive author has no public count/state');
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,false)$$,'P0001','NOT_FOUND','Inactive author prevents mutations');
reset role;
update private.user_access set status = 'active' where user_id = '3c000000-0000-4000-8000-000000000001';
update auth.users set email_confirmed_at = null where id = '3c000000-0000-4000-8000-000000000002';
set local role authenticated;
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,false)$$,'P0001','EMAIL_UNVERIFIED','Unverified actor denied');
reset role;
update auth.users set email_confirmed_at = now() where id = '3c000000-0000-4000-8000-000000000002';
set local role authenticated;
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000001',true)$$,'Actor blocks author');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Blocked target state is inaccessible');
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)$$,'P0001','NOT_FOUND','Block cannot be bypassed by direct RPC');
reset role;
select is((select count(*) from public.reactions where user_id = '3c000000-0000-4000-8000-000000000002'),0::bigint,'Blocking author removes actor reactions atomically');
set local role authenticated;
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000001',false)$$,'Unblock author');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'liked','false','Unblocking does not revive deleted reaction');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000001","session_id":"4c000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000003',true)$$,'Author blocks reactor');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','0','Reverse author block removes reaction too');
select lives_ok($$select public.set_user_block('3c000000-0000-4000-8000-000000000003',false)$$,'Author unblocks reactor');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000002","session_id":"4c000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,2,true)$$,'Restore only explicit new reaction');
reset role;
update public.tier_lists set moderation_status = 'hidden',version = version+1 where id = current_setting('tier_like.id')::uuid;
set local role authenticated;
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Moderation hides state and count');
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,3,true)$$,'P0001','NOT_FOUND','Hidden target cannot be liked');
reset role;
update public.tier_lists set moderation_status = 'visible',version = version+1 where id = current_setting('tier_like.id')::uuid;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000001","session_id":"4c000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.withdraw_tier_publication(current_setting('tier_like.id')::uuid,4,true)$$,'Withdraw publication');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Private target has no like state');
select set_config('tier_like.preview',public.preview_tier_publication(current_setting('tier_like.id')::uuid)::text,true);
select lives_ok($$select public.publish_tier_list(current_setting('tier_like.id')::uuid,1,5,current_setting('tier_like.preview')::jsonb->>'fingerprint','unlisted',true,jsonb_build_object('hash',repeat('a',64),'ciphertext',repeat('b',118),'nonce',repeat('c',24)),true)$$,'Publish token-only snapshot');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Link-only target has no state even for owner');
select is(public.get_tier_publication(current_setting('tier_like.id')::uuid,repeat('a',64),false,null)->'likeCount','null'::jsonb,'Valid link cannot reveal stored like count');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000002","session_id":"4c000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,6,true)$$,'P0001','NOT_FOUND','Link-only cannot be liked');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000001","session_id":"4c000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select set_config('tier_like.preview',public.preview_tier_publication(current_setting('tier_like.id')::uuid)::text,true);
select lives_ok($$select public.publish_tier_list(current_setting('tier_like.id')::uuid,1,6,current_setting('tier_like.preview')::jsonb->>'fingerprint','public',false,null,true)$$,'Return same tier list to public');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'likeCount','1','Visibility changes preserve valid tier-list reactions');
reset role;
delete from auth.sessions where user_id = '3c000000-0000-4000-8000-000000000002';
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000002","session_id":"4c000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,7,false)$$,'P0001','AUTH_REQUIRED','Removed session cannot mutate');
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid)->>'canLike','false','Removed session has a read-only public state');
reset role;
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000004","session_id":"4c000000-0000-4000-8000-000000000004","role":"authenticated"}',true);
set local role authenticated;
do $$begin for n in 1..40 loop perform public.set_tier_like(current_setting('tier_like.id')::uuid,7,true);end loop;end;$$;
select throws_ok($$select public.set_tier_like(current_setting('tier_like.id')::uuid,7,true)$$,'P0001','RATE_LIMITED','Rate limit cannot be bypassed by idempotent writes');
reset role;
select is((select count(*) from public.reactions where user_id = '3c000000-0000-4000-8000-000000000004'),1::bigint,'Rate fixture still has one reaction');
delete from auth.users where id = '3c000000-0000-4000-8000-000000000004';
select is((select count(*) from public.reactions where user_id = '3c000000-0000-4000-8000-000000000004'),0::bigint,'Account deletion cascades reactions');
select set_config('request.jwt.claims','{"sub":"3c000000-0000-4000-8000-000000000001","session_id":"4c000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select lives_ok($$select public.delete_tier_draft(current_setting('tier_like.id')::uuid,1,true)$$,'Soft-delete tier list');
reset role;
select is((select count(*) from public.reactions where tier_list_id = current_setting('tier_like.id')::uuid),0::bigint,'Soft deletion cleans all target reactions');
set local role authenticated;
select is(public.get_tier_like_state(current_setting('tier_like.id')::uuid),null::jsonb,'Deleted target is inaccessible');
reset role;
select * from finish();
rollback;
