import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowUp, BookOpen, Download, Eye, Palette, Pencil, Plus, Redo2, RotateCcw, Search, Settings2, Trash2, Undo2, Upload } from "lucide-react";
export const metadata = {title:"티어리스트"};
const rows = [
  {tier:"S",label:"신의 경지"}, {tier:"A",label:"강력 추천작"}, {tier:"B",label:"수작 인증"},
  {tier:"C",label:"취향작"}, {tier:"D",label:"아쉬운 점 있음"}, {tier:"F",label:"하차 / 취향 아님"},
] as const;
export default function Page() {
  return <div className="tier-preview-page"><section className="tier-preview-toolbar"><div className="page-container tier-toolbar-inner"><div className="tier-toolbar-title"><Link className="header-icon" href="/me/library" aria-label="내 서재로 돌아가기"><ArrowLeft size={18} aria-hidden="true"/></Link><div><h1>나만의 웹툰 티어표 <button type="button" disabled aria-label="제목 편집 · 준비 중"><Pencil size={14} aria-hidden="true"/></button></h1><p><span className="section-chip">디자인 미리 보기</span><span>작품 추가·편집·저장·공유 준비 중</span></p></div></div><div className="tier-toolbar-actions"><div className="tier-undo"><button type="button" disabled aria-label="실행 취소 · 준비 중"><Undo2 size={16} aria-hidden="true"/></button><button type="button" disabled aria-label="다시 실행 · 준비 중"><Redo2 size={16} aria-hidden="true"/></button></div><button className="button button-secondary" disabled>내 기본 평가 불러오기</button><button className="button button-secondary" disabled><Eye size={15} aria-hidden="true"/>미리보기</button><button className="button button-primary" disabled><Upload size={15} aria-hidden="true"/>게시하기 (공개 설정)</button></div></div></section>
    <div className="page-container tier-studio"><div className="tier-preview-layout"><aside className="tier-preview-pool"><div className="tier-pool-tabs"><button disabled>내 서재에서 추가</button><button disabled>전체 웹툰 검색</button></div><div className="tier-pool-filters"><label><Search size={16} aria-hidden="true"/><input disabled aria-label="서재 보관작 검색 · 준비 중" placeholder="서재 보관작 검색..."/></label><div><button disabled>완독</button><button disabled>보는 중</button><button disabled>★ 4.5 이상</button></div></div><div className="tier-pool-empty"><BookOpen size={28} aria-hidden="true"/><h2>배치할 작품을 기다리고 있어요.</h2><p>작품 추가 기능이 준비되면 내 서재에서 가져오거나 전체 작품을 검색할 수 있어요.</p><Link className="text-link" href="/me/library">내 서재 둘러보기 →</Link></div><Link className="tier-pool-footer" href="/submissions/new">외부 URL 또는 미등록 작품 제보</Link></aside>
      <section className="tier-preview-board" aria-labelledby="tier-board-title"><div className="tier-board-heading"><h2 id="tier-board-title">메인 티어 그리드 <span>아직 배치된 작품이 없어요</span></h2><div><button disabled><Plus size={13} aria-hidden="true"/>행 추가</button><button disabled><RotateCcw size={13} aria-hidden="true"/>리셋</button><button disabled><Palette size={13} aria-hidden="true"/>테마 색상</button></div></div><div className="tier-board-rows">{rows.map(({tier,label})=><div className="tier-preview-row" key={tier} data-tier={tier}><div className="tier-row-label"><strong>{tier}</strong><span>{label}</span></div><div className="tier-row-empty">비어 있음</div><div className="tier-row-tools"><button disabled aria-label={tier+" 행 위로 이동 · 준비 중"}><ArrowUp size={14} aria-hidden="true"/></button><button disabled aria-label={tier+" 행 아래로 이동 · 준비 중"}><ArrowDown size={14} aria-hidden="true"/></button><button disabled aria-label={tier+" 행 설정 · 준비 중"}><Settings2 size={14} aria-hidden="true"/></button></div></div>)}</div></section></div>
      <section className="tier-unplaced"><div><h2><BookOpen size={16} aria-hidden="true"/>미배치 작품 보관함 <span className="section-chip">준비 중</span></h2><p>공유 티어표의 배치는 개인 별점·기본 티어와 따로 기록해요.</p></div><p className="tier-unplaced-empty">작품 추가·배치·저장은 아직 사용할 수 없어요.</p><div className="tier-unplaced-footer"><span>미배치 작품은 최종 게시본에 포함되지 않아요.</span><button className="button button-secondary" disabled><Download size={14} aria-hidden="true"/>PNG 저장</button><button className="header-icon" disabled aria-label="미배치 작품 정리 · 준비 중"><Trash2 size={14} aria-hidden="true"/></button></div></section>
    </div>
  </div>;
}
