import Link from "next/link";
import type { CatalogueFilters, Platform } from "@/lib/catalogue/model";
import { ageLabels, dayLabels, filterUrl, serialLabels } from "@/lib/catalogue/model";
import { SearchBox } from "./search-box";

export function FilterForm({filters,options,disabled=false,total}:{filters:CatalogueFilters;options:{platforms:Platform[];genres:{id:string;slug:string;name:string}[]}|null;disabled?:boolean;total?:number}) {
  return <form action="/explore" method="get" className="catalogue-filters page-container">
    <div className="catalogue-search-row"><SearchBox key={JSON.stringify(filters)} initial={filters.q} filters={filters} disabled={disabled}/><button className="button button-primary" disabled={disabled}>검색</button></div>
    <fieldset className="catalogue-filter-fields" disabled={disabled}><legend className="sr-only">작품 검색 조건</legend>
      <fieldset className="catalogue-filter-row"><legend>플랫폼</legend><div className="filter-choices platform-choices"><Link className="filter-all" href={filterUrl({...filters,platform:[]})} aria-current={!filters.platform.length ? "page" : undefined}>전체</Link>{options?.platforms.map(p=><label key={p.id} data-platform={p.code}><input className="sr-only" type="checkbox" name="platform" value={p.code} defaultChecked={filters.platform.includes(p.code)}/><span className="platform-dot"/><span>{p.name}</span></label>)}{!options ? <p className="field-hint">등록된 플랫폼의 필터가 이곳에 표시돼요.</p> : null}</div></fieldset>
      <fieldset className="catalogue-filter-row"><legend>장르분류</legend><div className="filter-choices genre-choices"><Link className="filter-all" href={filterUrl({...filters,genre:[]})} aria-current={!filters.genre.length ? "page" : undefined}>전체</Link>{options?.genres.map(g=><label key={g.id}><input className="sr-only" type="checkbox" name="genre" value={g.slug} defaultChecked={filters.genre.includes(g.slug)}/><span>{g.name}</span></label>)}{!options ? <p className="field-hint">작품의 장르를 골라 좁혀 볼 수 있어요.</p> : null}</div></fieldset>
      <fieldset className="catalogue-filter-row"><legend>상태/요일</legend><div className="filter-status-days"><div className="filter-choices status-choices"><label><input className="sr-only" name="status" type="radio" value="" defaultChecked={filters.status === null}/><span>전체</span></label>{Object.entries(serialLabels).map(([value,label])=><label key={value}><input className="sr-only" type="radio" name="status" value={value} defaultChecked={filters.status === value}/><span>{label}</span></label>)}</div><div className="filter-choices day-choices">{dayLabels.map((label,index)=><label key={label}><input className="sr-only" type="checkbox" name="day" value={index} defaultChecked={filters.day.includes(index)}/><span>{label}</span></label>)}</div></div></fieldset>
      <fieldset className="catalogue-filter-row"><legend>연령/지표</legend><div className="filter-choices metric-choices"><label className="filter-age"><span className="sr-only">연령 범주</span><select name="age" defaultValue={filters.age ?? ""}><option value="">확인된 비성인 작품</option>{(["all","12","15"] as const).map(v=><option key={v} value={v}>{ageLabels[v]}</option>)}</select></label><span className="filter-unavailable">평점·독자 티어 필터 준비 중</span></div></fieldset>
    </fieldset>
    <div className="filter-footer"><div><p>{total === undefined ? "작품 카탈로그" : <>총 <strong>{total.toLocaleString("ko-KR")}</strong>개 작품</>}</p><Link className="text-link" href="/explore">선택된 필터 초기화</Link></div><div className="filter-sort"><label>정렬: <select name="sort" defaultValue={filters.sort} disabled={disabled}><option value="latest">최근 등록순</option><option value="title">제목순</option><option value="rating">평점순</option></select></label><button className="button button-secondary" disabled={disabled}>적용</button></div></div>
    {!disabled ? <p className="field-hint catalogue-rating-note">별점과 평가 수는 현재 볼 수 있는 공개 평가 기준이에요. {filters.sort === "rating" ? "평균이 높은 순서이며 평가가 없는 작품은 뒤에 표시돼요. " : ""}차단 설정에 따라 표시값이 달라질 수 있어요.</p> : null}
    <p className="sr-only">제목·별칭·작가명에 포함된 글자를 찾아요. 선택한 플랫폼과 요일은 같은 공식 링크에 적용돼요.</p>
  </form>;
}
