// @vitest-environment node
// Mocked route boundaries only. Does not execute Sharp or live DB/Auth/RLS.
import { beforeEach,describe,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({read:vi.fn(),render:vi.fn(),og:vi.fn(),generic:vi.fn(),publication:vi.fn()}));
vi.mock("@/lib/tiers/image-data",()=>({readTierImageSource:mocks.read}));
vi.mock("@/lib/tiers/image-render",()=>({renderTierPngs:mocks.render,renderTierOg:mocks.og,genericTierOg:mocks.generic}));
vi.mock("@/lib/tiers/publication-data",()=>({getTierPublication:mocks.publication}));
vi.mock("@/lib/env/public",()=>({getPublicEnv:()=>({siteUrl:"https://example.test"})}));
import { POST } from "@/app/api/tiers/[id]/export/route";
import { GET as publicOg } from "@/app/api/og/tiers/[id]/route";
import { GET as genericOg } from "@/app/api/og/tiers/route";
import { readImageRequest } from "@/lib/tiers/image-http";
import { tierImageMetadata } from "@/lib/tiers/image-metadata";
import { AuthFailure } from "@/lib/auth/errors";
const id="20000000-0000-4000-8000-000000000001",row="60000000-0000-4000-8000-000000000001";
const body={title:"private title",description:"",tags:[],rows:[{id:row,label:"S",colorToken:"S",canonicalTier:"S",items:[{title:"작품"}]},{id:"60000000-0000-4000-8000-000000000002",label:"A",colorToken:"A",canonicalTier:"A",items:[]}]};
const source={id,version:2,source:"draft",isSpoiler:true,body,unplaced:[]};
const input={source:"draft",version:2,token:null,confirm:true,confirmSpoiler:false};
const params={params:Promise.resolve({id})};
const request=(value:unknown=input,origin="https://example.test")=>new Request(`https://example.test/api/tiers/${id}/export`,{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify(value)});
const publication={id,version:2,publishedVersion:1,publishedAt:"2026-10-04T00:00:00Z",authorId:id,username:"author",name:"author",isSpoiler:true,body:null};
describe("tier image HTTP boundaries",()=>{
  beforeEach(()=>{vi.resetAllMocks();mocks.read.mockResolvedValue(source);mocks.render.mockResolvedValue([Buffer.from("png mock")]);mocks.generic.mockResolvedValue(Buffer.from("generic mock"));mocks.og.mockResolvedValue(Buffer.from("public mock"));mocks.publication.mockResolvedValue(publication);});
  it("rejects cross-origin, token-in-query, malformed/oversized and injected requests before rendering",async()=>{
    expect((await POST(request(input,"https://attacker.test"),params)).status).toBe(403);
    expect((await POST(request({...input,userId:id}),params)).status).toBe(400);
    expect((await POST(request({...input,description:"x".repeat(2100)}),params)).status).toBe(400);
    await expect(readImageRequest(new Request("https://example.test/api/tiers/id/export?token=secret",{method:"POST",headers:{origin:"https://example.test","content-type":"application/json"},body:JSON.stringify(input)}))).rejects.toMatchObject({code:"VALIDATION_ERROR"});
    expect(mocks.read).not.toHaveBeenCalled();expect(mocks.render).not.toHaveBeenCalled();
  });
  it("reserves account rate once and checks the current source again before returning a PNG",async()=>{
    const response=await POST(request(),params);expect(response.status).toBe(200);
    expect(mocks.read.mock.calls).toEqual([[id,input,true],[id,input]]);
    expect(response.headers.get("cache-control")).toContain("no-store");expect(response.headers.get("referrer-policy")).toBe("no-referrer");
    expect(response.headers.get("content-disposition")).toBe('attachment; filename="toonshelf-draft-v2.png"');
    expect(response.headers.get("x-toonshelf-pages")).toBe("1");
  });
  it("returns ZIP for multiple pages and accounts for the batch as one request",async()=>{
    mocks.render.mockResolvedValue([Buffer.from("first"),Buffer.from("second")]);const response=await POST(request(),params);
    expect(response.headers.get("content-type")).toBe("application/zip");expect(response.headers.get("x-toonshelf-pages")).toBe("2");
    expect(Buffer.from(await response.arrayBuffer()).readUInt32LE(0)).toBe(0x04034b50);
  });
  it("does not return generated bytes after content/visibility/session changes",async()=>{
    mocks.read.mockResolvedValueOnce(source).mockResolvedValueOnce({...source,body:{...body,title:"changed"}});
    let response=await POST(request(),params);expect(response.status).toBe(409);expect(response.headers.get("content-type")).toContain("application/json");
    mocks.read.mockResolvedValueOnce(source).mockRejectedValueOnce(new AuthFailure("NOT_FOUND","접근 불가"));
    response=await POST(request(),params);expect(response.status).toBe(404);
  });
  it("stops image work on account limits and exposes only safe errors",async()=>{
    mocks.read.mockRejectedValue(new AuthFailure("RATE_LIMITED","잠시 후 다시 시도해 주세요."));const response=await POST(request(),params);
    expect(response.status).toBe(429);expect(response.headers.get("retry-after")).toBe("600");expect(mocks.render).not.toHaveBeenCalled();
    mocks.read.mockRejectedValue(new Error("database token private title"));expect(await (await POST(request(),params)).text()).not.toContain("database token");
  });
  it("keeps spoiler/unlisted OG generic and never passes a token to public OG lookup",async()=>{
    let response=await publicOg(new Request(`https://example.test/api/og/tiers/${id}`),params);expect(response.status).toBe(200);
    expect(mocks.generic).toHaveBeenCalled();expect(mocks.og).not.toHaveBeenCalled();expect(mocks.publication.mock.calls).toEqual([[id],[id]]);
    mocks.publication.mockResolvedValue(null);response=await publicOg(new Request(`https://example.test/api/og/tiers/${id}`),params);expect(response.status).toBe(404);
    response=await publicOg(new Request(`https://example.test/api/og/tiers/${id}?token=secret`),params);expect(response.status).toBe(404);
    expect((await genericOg(new Request("https://example.test/api/og/tiers"))).status).toBe(200);
    expect(JSON.stringify(tierImageMetadata(null))).not.toContain(id);expect(JSON.stringify(tierImageMetadata(null))).toContain('"https://example.test/api/og/tiers"');
  });
  it("renders only non-spoiler current public titles and rejects a withdrawn result",async()=>{
    const publicBody={...body,rows:body.rows.map(r=>({...r,items:r.items.map(w=>({...w,id,slug:"work",coverAssetId:"secret-asset",creators:[],platforms:[],genres:[],ratingAverage:null,ratingCount:0}))}))};
    mocks.publication.mockResolvedValueOnce({...publication,isSpoiler:false,body:publicBody}).mockResolvedValueOnce(null);
    const response=await publicOg(new Request(`https://example.test/api/og/tiers/${id}`),params);expect(response.status).toBe(404);
    expect(mocks.og.mock.calls[0]![0].body.rows[0].items).toEqual([{title:"작품"}]);
    expect(JSON.stringify(mocks.og.mock.calls[0]![0])).not.toContain("secret-asset");
  });
});
